create table users (
   id BIGINT AUTO_INCREMENT PRIMARY KEY ,
    username VARCHAR(255) NOT NULL UNIQUE ,
   email VARCHAR(255) NOT NULL UNIQUE ,
   password VARCHAR(255) NOT NULL ,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    role VARCHAR(20) NOT NULL
    );